### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by CPZ-0** [NJU-LHRS/LHRS-Bot#32]
您好，我在进行第二步训练时遇到了如下的报错
Traceback (most recent call last):
  File "/home/chenpengzhou/bupt-airs-bot-main/Script/../main_pretrain_stage2.py", line 312, in <module>
    main(config)
  File "/home/chenpengzhou/bupt-airs-bot-main/Script/../main_pretrain_stage2.py", line 261, in main
    trainer.train(load_checkpoint=config.resume_path)
  File "/home/chenpengzhou/bupt-airs-bot-main/lhrs/CustomTrainer/trainer.py", line 488, in train
    self.sub_classes_train()
  File "/home/chenpengzhou/bupt-airs-bot-main/lhrs/CustomTrainer/EpochBasedTrainer.py", line 108, in sub_classes_train
    self._train_one_epoch()
  File "/home/chenpengzhou/bupt-airs-bot-main/lhrs/CustomTrainer/EpochBasedTrainer.py", line 98, in _train_one_epoch
    self.train_on_iter()
  File "/home/chenpengzhou/bupt-airs-bot-main/lhrs/CustomTrainer/trainer.py", line 460, in train_on_iter
    self.loss_dict = self.model(batch)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1909, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenpengzhou/bupt-airs-bot-main/lhrs/models/UniBind.py", line 189, in forward
    output = getattr(self, modal)(
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenpengzhou/bupt-airs-bot-main/lhrs/models/base_modal.py", line 51, in forward
    return self.decode(
  File "/home/chenpengzhou/bupt-airs-bot-main/lhrs/models/text_modal.py", line 281, in decode
    outputs = self.text_encoder(
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/peft/peft_model.py", line 1073, in forward
    return self.base_model(
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 103, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1181, in forward
    outputs = self.model(
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1058, in forward
    layer_outputs = self._gradient_checkpointing_func(
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 451, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 230, in forward
    outputs = run_function(*args)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 796, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 691, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/peft/tuners/lora/bnb.py", line 157, in forward
    result = self.base_layer(x, *args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 454, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 562, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 344, in forward
    state.CxB, state.SB = F.transform(state.CB, to_order=formatB)
  File "/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/bitsandbytes/functional.py", line 2196, in transform
    prev_device = pre_call(A.device)
AttributeError: 'NoneType' object has no attribute 'device'
请问您有什么头绪吗

**Comment by pUmpKin-Co** [comment]
您好，我能看一下config嘛。

我这边测试了一下是正常的。

**Comment by CPZ-0** [comment]
# Control
alignment_dim: 768
adjust_norm: False
generate: False
prompt_template: "llava_llama_2"
stage: 2
weight_sample: False

# Tune Parameter
tune_im_start: False
tune_im_patch: False
tune_rgb_bk: False
tune_rgb_pooler: True  # True for stage2

rgb_vision:
  arch: vit_large 
  vit_name: openai/clip-vit-large-patch14  # if use vit, choice the pre-trained model source
  input_size: [224, 224]
  patch_dropout: 0.
  input_patchnorm: False
  tune_pooler: True
  attn_pooler:
    num_query: 144
    num_attn_heads: 16
    num_layers: 6
text:
  # llama-v2 config
  vocab_size: 32000
  hidden_size: 4096
  intermediate_size: 11008
  num_hidden_layers: 32
  num_attention_heads: 32
  hidden_act: "silu"
  max_position_embeddings: 2048
  initializer_range: 0.02
  rms_norm_eps: 1e-5
  use_cache: True
  pad_token_id: 0
  bos_token_id: 1
  eos_token_id: 2
  tie_word_embeddings: False
  path: ../meta-llama/Llama-2-7b-chat-hf
sar_vision:
  arch: base
  input_size: [192, 192]
  n_queries: 256
  in_chans: 2
  # decoder Parameter
  decoder:
    layers: 12
    heads: 12
    mask_ratio: 0.6
    mask_color: mean
    hidden_size: 768
  # loss Parameter
  loss_weight: 1.0
  reduction: none
  activate: sigmoid
  alpha: 0.2
  focal_gamma: 1.0
  residual: False
  unmask_weight: 0.0
  # DINO Contrastive Learning Parameter
  online_temp: 0.1
  branch_temp: 0.07
  warmup_branch_temp: 0.04
  warmup_branch_temp_epochs: 2
transform:
  input_size: [224, 224]
  rand_aug: rand-m5-n2-mstd0.5-inc1
eval:
  dataset: AID

# training config
dtype: float16
bits: 8
double_quant: True
quant_type: nf4
fp16: True
bf16: False
lora:
  enable: True  # True for stage 2
  lora_r: 128
  lora_alpha: 256
  lora_dropout: 0.05
  lora_bias: none

# optimizer
optimizer: adamw
lr: 0.0002
wd: 0.
epochs: 1
max_grad_norm: 1.0
betas: [0.9, 0.95]

# scheduler
schedule:
  name: cosine
  min_lr: 0.00008
  warmup_epochs: 100
  warmup_method: linear
  warmup_factor: 0.01
  decay_epochs: 30
  decay_rate: 0.1
  multisteps: []
  gamma: 0.1
这是stage2的config文件

**Comment by pUmpKin-Co** [comment]
您好，把bit改成16会有同样的问题吗？

**Comment by CPZ-0** [comment]
您好，感谢您的回复，这个给问题已经解决了，是bitsandbytes库有一些兼容问题

**Comment by CPZ-0** [comment]
> 您好，我在进行第二步训练时遇到了如下的报错 Traceback （most recent call last）： File “/home/chenpengzhou/bupt-airs-bot-main/Script/../main_pretrain_stage2.py“，第 312 行，在 main（config） 文件中 ”/home/chenpengzhou/bupt-airs-bot-main/Script/../main_pretrain_stage2.py“，第 261 行，在 main trainer.train（load_checkpoint=config.resume_path） 文件 ”/home/chenpengzhou/bupt-airs-bot-main/lhrs/CustomTrainer/trainer.py“，第 488 行，在火车self.sub_classes_train（） 文件中 ”/home/chenpengzhou/bupt-airs-bot-main/lhrs/CustomTrainer/EpochBasedTrainer.py“，第 108 行，sub_classes_train self._train_one_epoch（）文件 “/home/chenpengzhou/bupt-airs-bot-main/lhrs/CustomTrainer/EpochBasedTrainer.py”，第 98 行，_train_one_epoch self.train_on_iter（） 文件“/home/chenpengzhou/bupt-airs-bot-main/lhrs/CustomTrainer/trainer.py”，第 460 行，train_on_iter self.loss_dict = self.model（batch） 文件“/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回 forward_call（*args， **kwargs） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/deepspeed/utils/nvtx.py”，第 18 行，wrapped_fn ret_val = func（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/deepspeed/runtime/engine.py”，第 1909 行，正向丢失 = self.module（*inputs， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回 forward_call（*args， **kwargs）文件 “/home/chenpengzhou/bupt-airs-bot-main/lhrs/models/UniBind.py”，第 189 行，前向输出 = getattr（self， modal）（ 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，在 _wrapped_ 中call_impl 返回 self._call_impl（*args， **kwargs） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回 forward_call（*args， **kwargs） 文件 “/home/chenpengzhou/bupt-airs-bot-main/lhrs/models/base_modal.py”，第 51 行，向前返回 self.decode（文件 “/home/chenpengzhou/bupt-airs-bot-main/lhrs/models/text_modal.py”，第 281 行，解码输出 = self.text_encoder（ 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回 forward_call（*args， **kwargs） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/peft/peft_model.py“，第 1073 行，正向返回 self.base_model（ 文件 ”/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py“，第 1518 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs） 文件 ”/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py“，第 1527 行，_call_impl返回forward_call（*args， **kwargs） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/peft/tuners/tuners_utils.py”，第 103 行，向前返回 self.model.forward（*args， **kwargs） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/accelerate/hooks.py”，第 165 行，new_forward输出 = module._old_forward（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py”，第 1181 行，前向输出 = self.model（ 文件“/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回 forward_call（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/accelerate/hooks.py”，第 165 行，new_forward输出 = module._old_forward（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py”，第 1058 行，前向 layer_outputs = self._gradient_checkpointing_func（ 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/_compile.py”，第 24 行，内部返回 torch._dynamo.disable（fn， recursive）（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py”，第 328 行，_fn返回 fn（*args， **kwargs） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/_dynamo/external_utils.py”，第 17 行，内部返回 fn（*args， **kwargs） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/utils/checkpoint.py”， 第 451 行，在检查点返回 CheckpointFunction.apply（function， preserve， *args） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/autograd/function.py”，第 539 行，在 apply 中 return super（）.apply（*args， **kwargs） # 类型：ignore[misc] 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/utils/checkpoint.py”，第 230 行，在前向输出中 = run_function（*args） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，_wrapped_call_impl 返回 self._call_impl（*args， **kwargs） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回forward_call（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/accelerate/hooks.py”，第 165 行，new_forward输出 = module._old_forward（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py”，第 796 行，正向hidden_states，self_attn_weights，present_key_value = self.self_attn（文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回forward_call（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/accelerate/hooks.py”，第 165 行，new_forward输出 = module._old_forward（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py”，第 691 行，正向query_states = self.q_proj（hidden_states）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回forward_call（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/peft/tuners/lora/bnb.py”，第 157 行，前向结果 = self.base_layer（x， *args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1518 行，_wrapped_call_impl返回 self._call_impl（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/nn/modules/module.py”，第 1527 行，_call_impl返回 forward_call（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/accelerate/hooks.py”，第 165 行，new_forward输出 = module._old_forward（*args， **kwargs）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/bitsandbytes/nn/modules.py”，第 454 行，传入转发 out = bnb.matmul（x， self.weight， bias=self.bias， state=self.state）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py”，第 562 行，在 matmul 中返回 MatMul8bitLt.apply（A， B， out， bias， state）文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/torch/autograd/function.py”，第 539 行，在 apply return super（）.apply（*args， **kwargs） # 类型：ignore[misc] 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py”，第 344 行，处于转发状态。CxB，状态。SB = F.transform（状态.CB， to_order=formatB） 文件 “/home/chenpengzhou/anaconda3/envs/bupt_airs/lib/python3.10/site-packages/bitsandbytes/functional.py”，第 2196 行，转换中prev_device = pre_call（A.device） AttributeError： 'NoneType' object has no attribute 'device' 请问您有什么头绪吗

**Comment by aysim** [comment]
Hey, I'm running into the same compatibility issue. How did you end up resolving it?
